### PR TITLE
New progress bar and space estimation

### LINKED ISSUE #107: Display an estimation for runtime
Can be an estimation of total number of interleavings, or even better expected completion time.

Ideally will report "confidence" in the estimation too.

### LINKED ISSUE #116: Fix Concuerror's printout in console
Console printout can be improved in the following ways:
* <s>Correctly adjust with the size of the console window</s>
* Use a better layout with labels and numbers updated below those labels

### PR DESCRIPTION
**Pull request by aronisstav**
## Summary

Improve the look of the progress bar and add total state space size and time to completion estimations.

Fixes #107.
Fixes #116.

## Checklist

* [x] Has tests
* [x] Updates CHANGELOG
* [x] References related Issues

### CODE REVIEW

**Comment by kostis** [comment]
On sandy, `tests-real` fail miserably for me:
<pre>
make tests-real 
make -j 1 -C tests-real \
        CONCUERROR=/home/kostis/HiPE/Concuerror/bin/concuerror \
        DIFFER=/home/kostis/HiPE/Concuerror/tests/differ \
        DIFFPRINTER=/home/kostis/HiPE/Concuerror/tests-real/thediff
make[1]: Entering directory '/home/kostis/HiPE/Concuerror/tests-real'
make -C suites/output/
make[2]: Entering directory '/home/kostis/HiPE/Concuerror/tests-real/suites/output'
./output-tests
./output-tests
Progress bar sample...ok
... and output has "    Errors |  Explored | Planned |  ~ Rate |  Total(?) | Time(?)"...ok
... and output has "         0 |         0 |       1 |   <1 /s |   unknown | unknown"...
cat concuerror_report.txt
Concuerror v0.18-249-gb26274 started at 24 Apr 2018 10:07:49

-----------------------------------------------------------------
    Errors |  Explored | Planned |  ~ Rate |  Total(?) | Time(?) 
-----------------------------------------------------------------

         0 |         0 |       0 |   <1 /s |   unknown | unknown
         0 |        41 |       7 |   10 /s |   unknown | unknown
         0 |       652 |       5 |  131 /s |       660 |     <1m
Done at 24 Apr 2018 10:07:50 (Exit status: ok)
  Summary: 0 errors, 720/720 interleavings explored
ict_scheduling,false},
   {symbolic_names,true},
   {timeout,5000},
   {treat_as_normal,[]},
   {use_receive_patterns,true}]
################################################################################
Exploration completed!
  No errors found!
################################################################################
Warnings:
--------------------------------------------------------------------------------
* Some errors were ignored ('--ignore_error').

################################################################################
Tips:
--------------------------------------------------------------------------------
* Running without a scheduling_bound corresponds to verification and may take a long time.

################################################################################
Info:
--------------------------------------------------------------------------------
* Showing progress (-h progress, for details)
* Writing results in concuerror_report.txt
* Automatically instrumented module io_lib
* Showing PIDs as "<symbolic name(/last registered name)>" ('-h symbolic_names').
* Instrumented & loaded module many_scheds
* Automatically instrumented module lists
* Automatically instrumented module erlang
* You can see pairs of racing instructions (in the report and '--graph') with '--show_races true'

################################################################################
Done at 24 Apr 2018 10:07:50 (Exit status: ok)
  Summary: 0 errors, 720/720 interleavings explored
cat console
cat: console: No such file or directory
FAILED
Makefile:3: recipe for target 'test' failed
make[2]: *** [test] Error 1
make[2]: Leaving directory '/home/kostis/HiPE/Concuerror/tests-real/suites/output'
Makefile:8: recipe for target 'suites/output/' failed
make[1]: *** [suites/output/] Error 2
make[1]: Leaving directory '/home/kostis/HiPE/Concuerror/tests-real'
Makefile:125: recipe for target 'tests-real' failed
make: *** [tests-real] Error 2
</pre>

Is it just me?

**Comment by aronisstav** [comment]
No, will patch, together with some fix for the new deprecation of
get_stacktrace for OTP 21.

**Comment by kostis** [comment]
FYI: this is with Erlang/OTP 19, so it's definitely not related to newly deprecated functions and warnings as errors.

**Comment by aronisstav** [comment]
These are indeed two unrelated issues.

The failure you're seeing is most likely due to you running Concuerror on bare-metal on a fast machine. These days I am mostly using a slow laptop and Travis' containers, so I didn't catch the bug.

**Comment by kostis** [comment]
OK -- but please try to include this fix *together* with this PR.

**Comment by aronisstav** [comment]
#244 has two commits. One removes warnings_as_errors from default and adds a separate test for them, the other fixes the bug you're seeing.

**Comment by kostis** [comment]
Removing `warnings_as_errors` is a bad idea -- there are better fixes that can be done.
Also, as I wrote, the proper thing to do is to add the fix for the bug together with this PR; it's on top of the `master` branch anyway, so it can be taken out and put back in properly.

**Comment by aronisstav** [comment]
`+warnings_as_errors` is still tested as part of the suite and it will fail Travis if a warning appears on known releases. Having it on by default everywhere is annoying for people working on bleeding edge, unless I always prioritize fixing such bugs when I encounter them, which I can't.

I am not sure I understand what you mean by "taken out". This PR has been merged and `master` only moves forward.

**Comment by kostis** [comment]
> I am not sure I understand what you mean by "taken out". This PR has been merged and master only moves forward.

I think this is the wrong policy.  IMO, a better one is that PRs should *never* break the tests, which means that they should contain all fixes that they require for this (in the same PR).

By the way, even after #244 has been merged, I still get failures in `tests-real`.  Just different ones, perhaps some we may have had all along:
<pre>
mailbox/msg_msg_indirect.erl                                 possible_1  ok     
mailbox/msg_demonitor_info.erl                               exhaustive  ok     
./test: line 21: 21392 Segmentation fault      ../../run_litmus.escript $1
Concuerror v0.18-252-gb0933f started at 24 Apr 2018 12:25:08
...
################################################################################
Info:
--------------------------------------------------------------------------------
* Automatically instrumented module io_lib
* Showing PIDs as "<symbolic name(/last registered name)>" ('-h symbolic_names').
* Instrumented & loaded module msg_demonitor
* Automatically instrumented module erlang

################################################################################
Done at 18 Apr 2018 16:53:04 (Exit status: error)
  Summary: 1 errors, 1/1 interleavings explored
FAILED
Makefile:4: recipe for target 'test' failed
make[2]: *** [test] Error 139
make[2]: Leaving directory '/home/kostis/HiPE/Concuerror/tests-real/suites/erlang-litmus'
Makefile:8: recipe for target 'suites/erlang-litmus/' failed
make[1]: *** [suites/erlang-litmus/] Error 2
make[1]: Leaving directory '/home/kostis/HiPE/Concuerror/tests-real'
Makefile:126: recipe for target 'tests-real' failed
make: *** [tests-real] Error 2
</pre>

So, I still think that we need better testing procedures, and that perhaps today's merges should not have happened, the way they did.

**Comment by aronisstav** [comment]
Moving master only forward is non-negotiable. Improving the testing pipeline to catch more errors is, on the contrary, always desirable.

I rely on Travis because I want everything to be automatic and also visible to anyone sending PRs. Testing on Uppsala's `sandy` machine is therefore not currently included and neither is testing on an up-to-date OTP-`master` release.

Suggestions to make such (or other equivalent) tests automatic are welcome. I will, for the time being, add some way of reminding me to do such tests manually before merging.

**Pull request merged**
