### PR TITLE
Observers

### LINKED ISSUE #154: Fix using receive patterns for optimal DPOR
Also:

* Remove experimental references in options
* Remove defaulting to source from options

### PR DESCRIPTION
**Pull request by aronisstav**
Closes #154.

### CODE REVIEW

**Comment by aronisstav** [comment]
@kostis take a look

**Comment by kostis** [comment]
I will look only if you prompt me again :-)

**Comment by aronisstav** [comment]
Prompt

**Comment by aronisstav** [comment]
@kostis

**Comment by aronisstav** [comment]
Ping

**Comment by aronisstav** [comment]
Pong

**Pull request merged**
